@Cookaracha.Api_HostAddress = https://localhost:1337

### Get application name

GET {{Cookaracha.Api_HostAddress}}/home
Accept: application/json

### Get all products

GET {{Cookaracha.Api_HostAddress}}/products
Accept: application/json

### Get product by id

GET {{Cookaracha.Api_HostAddress}}/products/bb27c9b2-9f0b-4c5d-99e5-7be8cb9e29d7
Accept: application/json

### Create new product

POST {{Cookaracha.Api_HostAddress}}/products
Content-Type: application/json
{
    "name": "Pineapple"
}

### Update product

PUT {{Cookaracha.Api_HostAddress}}/products/bb27c9b2-9f0b-4c5d-99e5-7be8cb9e29d7
Content-Type: application/json
{
    "name": "Peach"
}

### Delete product

DELETE {{Cookaracha.Api_HostAddress}}/products/00000000-0000-0000-0000-000000000001
Accept: application/json