@ApiUrl = https://localhost:1337
@ProductId = 00000000-0000-0000-0000-000000000001
@GroceryListId = 00000000-0000-0000-0000-000000000001
@ItemId = 00000000-0000-0000-0000-000000000001

### Get application name

GET {{ApiUrl}}
Accept: application/json

### Get all products

GET {{ApiUrl}}/api/products
Accept: application/json

### Get product by id

GET {{ApiUrl}}/api/products/{{ProductId}}
Accept: application/json

### Create new product

POST {{ApiUrl}}/api/products
Content-Type: application/json
{
    "name": "Pineapple"
}

### Update product

PUT {{ApiUrl}}/api/products/{{ProductId}}
Content-Type: application/json
{
    "name": "Peach"
}

### Delete product

DELETE {{ApiUrl}}/api/products/{{ProductId}}
Accept: application/json

### Get all grocery lists

GET {{ApiUrl}}/api/grocery-lists
Accept: application/json

### Get grocery list by id

GET {{ApiUrl}}/api/grocery-lists/{{GroceryListId}}
Accept: application/json

### Create new grocery list

POST {{ApiUrl}}/api/grocery-lists
Content-Type: application/json
{
    "name": "My grocery list",
    "items": [
        {
            "name": "Apple",
            "quantity": 2137,
            "productId": "{{ProductId}}",
            "product": {
              "id": "{{ProductId}}",
              "name": "Orange"
            }
        },
        {
            "name": "Pear",
            "quantity": 2137
        }
    ]
}

### Update grocery list

PUT {{ApiUrl}}/api/grocery-lists/{{GroceryListId}}
Content-Type: application/json
{
    "name": "My edited grocery list"
}

### Delete grocery list

DELETE {{ApiUrl}}/api/grocery-lists/{{GroceryListId}}
Accept: application/json

### Get item by id

GET {{ApiUrl}}/api/grocery-lists/{{GroceryListId}}/items/{{ItemId}}
Accept: application/json

### Create item

POST {{ApiUrl}}/api/grocery-lists/{{GroceryListId}}/items
Content-Type: application/json
{
    "name": "Lime",
    "quantity": 1337
}

### Update item

PUT {{ApiUrl}}/api/grocery-lists/{{GroceryListId}}/items/{{ItemId}}
Content-Type: application/json
{
    "name": "Grapes",
    "quantity": 2137
}

### Delete tiem

DELETE {{ApiUrl}}/api/grocery-lists/{{GroceryListId}}/items/{{ItemId}}
Accept: application/json
